# Generated by Django 4.2.7 on 2024-10-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("created_at_time", models.BigIntegerField()),
                ("timestamp", models.BigIntegerField()),
                ("cause", models.TextField()),
                ("full_name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("invoice_url", models.URLField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
